apiVersion: v1
kind: Secret
metadata:
  name: tutorial-registry-credentials
  annotations:
    build.pivotal.io/docker: gcr.io
type: kubernetes.io/basic-auth
data:
  # echo -n "_json_key" | base64 - | pbcopy
  username: X2pzb25fa2V5
  # base64 -i gcp-sa-gcr.json -o - | pbcopy
  password: <snip>

---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: tutorial-service-account
secrets:
 - name: tutorial-registry-credentials
