apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-common.yaml
- 02-contour.yaml
- 02-rbac.yaml
- 02-service.yaml

namespace: vmware-contour

commonLabels:
  app: mycontour
  env: tgik
