---
apiVersion: v1
kind: Namespace
metadata:
  name: basens
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerCluster
metadata:
  name: base
  namespace: basens
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: base
  namespace: basens
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerCluster
    name: base
