apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-np
  name: nginx-np
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
